import { ArrowRight, Layers3, MousePointer2, Play } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "../components/atoms/Button";
import { SiteHeader } from "../components/organisms/SiteHeader";

export function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-zinc-950 text-zinc-100"><SiteHeader /><section className="mx-auto grid min-h-[calc(100vh-80px)] max-w-7xl items-center gap-14 px-6 pb-20 pt-10 lg:grid-cols-[.9fr_1.1fr]">
    <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-lime-300/20 bg-lime-300/5 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.16em] text-lime-300"><span className="size-1.5 rounded-full bg-lime-300" />Local-first motion editor</div><h1 className="select-text max-w-2xl text-5xl font-bold leading-[.95] tracking-[-.065em] sm:text-7xl">Motion design,<br /><span className="text-zinc-500">without the mess.</span></h1><p className="select-text mt-7 max-w-lg text-sm leading-6 text-zinc-500">Build vector animations on a focused canvas. Your projects stay in your browser, ready whenever you come back.</p><div className="mt-9 flex gap-3"><Link to="/projects"><Button className="h-11 gap-2 bg-lime-300 px-5 text-zinc-950 hover:bg-lime-200">Start creating<ArrowRight className="size-4" /></Button></Link><a href="#preview"><Button className="h-11 gap-2 border border-white/10 px-5 text-zinc-300"><Play className="size-3.5 fill-current" />See the editor</Button></a></div><div className="mt-12 flex gap-8 text-[10px] text-zinc-600"><span className="flex items-center gap-2"><Layers3 className="size-3.5 text-violet-400" />Vector layers</span><span className="flex items-center gap-2"><MousePointer2 className="size-3.5 text-lime-300" />Direct control</span></div></div>
    <div id="preview" className="relative"><div className="absolute -inset-12 bg-[radial-gradient(circle,#7557f622,transparent_65%)]" /><div className="relative overflow-hidden rounded-2xl border border-white/10 bg-zinc-900 p-2 shadow-2xl"><div className="flex h-10 items-center gap-1.5 border-b border-white/10 px-3"><i className="size-2 rounded-full bg-red-400/70" /><i className="size-2 rounded-full bg-amber-300/70" /><i className="size-2 rounded-full bg-lime-300/70" /><span className="ml-3 text-[8px] text-zinc-600">Summer motion</span></div><div className="grid aspect-[1.45] grid-cols-[22%_1fr] grid-rows-[1fr_25%]"><div className="border-r border-white/10 p-3"><span className="text-[7px] uppercase tracking-widest text-zinc-600">Layers</span>{["Hero scene", "Sun orb", "Flowing path", "Main title"].map((name, index) => <div key={name} className={`mt-2 rounded px-2 py-1.5 text-[7px] ${index === 2 ? "bg-white/10 text-zinc-200" : "text-zinc-600"}`}>{name}</div>)}</div><div className="grid place-items-center bg-[#111116] p-8"><div className="relative aspect-video w-full overflow-hidden bg-[#f4efdf]"><div className="absolute right-[10%] top-[14%] size-[30%] rounded-full bg-[#ff795f]" /><div className="absolute left-[8%] top-[28%] text-[clamp(13px,2.6vw,34px)] font-bold leading-none tracking-tighter text-[#17131f]">Shape ideas<br />into motion.</div><div className="absolute -bottom-[8%] -left-[5%] h-[38%] w-[115%] -rotate-6 rounded-[50%] bg-violet-500" /></div></div><div className="col-span-2 border-t border-white/10 p-3"><div className="h-2 w-full bg-[linear-gradient(90deg,transparent_0_15%,#7557f6_15%_70%,transparent_70%)]" /><div className="mt-2 h-2 w-full bg-[linear-gradient(90deg,transparent_0_28%,#315d91_28%_78%,transparent_78%)]" /></div></div></div></div>
  </section></main>;
}
