import { Pause, Play, SkipBack, SkipForward } from "lucide-react";
import type { Layer } from "../../editor/model";
import { formatTime } from "../../editor/model";
import { cn } from "../../lib/cn";
import { Button } from "../atoms/Button";
import { LayerIcon } from "../atoms/LayerIcon";

export function TimelinePanel({ layers, selected, time, playing, onSelect, onTime, onPlaying }: { layers: Layer[]; selected: string; time: number; playing: boolean; onSelect: (id: string) => void; onTime: (time: number) => void; onPlaying: (playing: boolean) => void }) {
  const tracks = layers.filter((layer) => layer.type !== "group").slice(0, 3);
  return <section className="grid size-full grid-cols-[238px_1fr] grid-rows-[43px_1fr] bg-zinc-900 max-[900px]:grid-cols-[190px_1fr] max-[650px]:grid-cols-[115px_1fr]">
    <div className="col-span-full grid grid-cols-[238px_1fr_auto] items-center border-b border-white/10 max-[900px]:grid-cols-[190px_1fr_auto] max-[650px]:grid-cols-[115px_1fr_auto]"><div className="flex justify-center gap-1"><Button className="size-6 text-zinc-600" onClick={() => onTime(Math.max(0, time - 1 / 30))}><SkipBack className="size-3" /></Button><Button className="size-6 rounded-full bg-lime-300 text-zinc-950 hover:bg-lime-200" onClick={() => onPlaying(!playing)}>{playing ? <Pause className="size-3 fill-current" /> : <Play className="size-3 fill-current" />}</Button><Button className="size-6 text-zinc-600" onClick={() => onTime(Math.min(5, time + 1 / 30))}><SkipForward className="size-3" /></Button></div><div className="flex gap-1.5 pl-3 font-mono text-[9px]"><strong className="text-lime-300">{formatTime(time)}</strong><span className="text-zinc-700">/ 00:05:00</span></div><Button className="mr-3 text-[8px] text-zinc-600" onClick={() => onTime(0)}>Reset</Button></div>
    <div className="min-w-0 border-r border-white/10 pt-6">{tracks.map((layer) => <button key={layer.id} onClick={() => onSelect(layer.id)} className={cn("flex h-[42px] w-full min-w-0 items-center gap-2 px-3.5 text-left text-[9px] text-zinc-500", selected === layer.id && "bg-white/5 text-zinc-200")}><LayerIcon type={layer.type} /><span className="select-text truncate">{layer.name}</span></button>)}</div>
    <div className="relative overflow-hidden bg-[linear-gradient(90deg,#25252c_1px,transparent_1px)] bg-size-[10%_100%] pt-6" onPointerDown={(event) => { const rect = event.currentTarget.getBoundingClientRect(); onTime(Math.max(0, Math.min(5, (event.clientX - rect.left) / rect.width * 5))); }}><div className="absolute inset-x-0 top-0 h-6 border-b border-white/10">{[0, 1, 2, 3, 4, 5].map((tick) => <span key={tick} className="absolute top-1.5 font-mono text-[7px] text-zinc-600" style={{ left: `${tick * 20}%` }}>{tick}s</span>)}</div><div className="pointer-events-none absolute bottom-0 top-0 z-10 w-px bg-lime-300" style={{ left: `${time / 5 * 100}%` }}><span className="absolute -left-1 top-0 size-2 rounded-b-full bg-lime-300" /></div>{tracks.map((layer, index) => <div key={layer.id} className="relative h-[42px] border-b border-white/5"><button onClick={(event) => { event.stopPropagation(); onSelect(layer.id); }} className={cn("absolute top-2 h-6 rounded border bg-violet-950/70", index === 0 ? "border-red-400/70 bg-red-950/60" : index === 2 ? "border-blue-400/70 bg-blue-950/60" : "border-violet-400/70", selected === layer.id && "ring-1 ring-lime-300")} style={{ left: `${layer.start / 5 * 100}%`, width: `${layer.duration / 5 * 100}%` }}><i className="absolute left-1 top-2 size-1.5 rotate-45 bg-zinc-200" /><i className="absolute right-1 top-2 size-1.5 rotate-45 bg-zinc-200" /></button></div>)}</div>
  </section>;
}
